name: Docker Build and Push to ECR

on:
  workflow_call:
    inputs:
      dockerPath:
        type: string
        required: true
        default: Dockerfile
      environmentName:
        type: string
        required: true

env:
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  ECS_SERVICE: ${{ secrets.ECS_SERVICE}}
  ECS_CLUSTER: ${{secret.ECS_CLUSTER}}
  ECS_TASK_DEFINITION: ${{ secrets.ECS_TASK_DEFINITION }}
  ECS_CONTAINER_NAME: ${{ secrets.ECS_CONTAINER_NAME }}


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    environment: ${{ inputs.environmentName }} 

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}
          tags: |
            type=sha
            type=raw,value=latest

      - name: Extract image tag
        id: image
        run: |
          TAG=$(echo "${{ steps.meta.outputs.tags }}" | head -n1)
          echo "image=$TAG" >> $GITHUB_OUTPUT      

      # ---> PASSO ADICIONADO: Criando o arquivo .env <---
      - name: Create .env file
        run: echo "${{ secrets.ENVS }}" > .env

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: "${{ inputs.dockerPath }}"
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Download current task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition ${{ env.ECS_TASK_DEFINITION }} \
            --query taskDefinition > task-definition.json

      - name: Render new task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ env.ECS_CONTAINER_NAME }}
          image: ${{ steps.image.outputs.image }}

      - name: Deploy ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true     